# Generated by Django 4.1.5 on 2023-12-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userfile_user_alter_userfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
